live_config_reload = true

import = [
    "~/.config/alacritty/themes/themes/kanagawa_wave.toml"
]


[font]
size = 16.0

[font.bold]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
style = "Regular"

[font.offset]
x = 1
y = 1

[scrolling]
history = 5000
multiplier = 10

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
program = "zsh"
args = ["-l", "-c", "tmux && tmux source ~/.config/tmux/.tmux.conf"]

[window]
decorations = "None"
opacity = 1.0
startup_mode = "Fullscreen"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 160
lines = 95

[window.padding]
x = 5
y = 5

[window.position]
x = 0
y = 80
