;;; kanagawa-themes-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from kanagawa-themes.el

(defvar kanagawa-themes-custom-colors 'nil "\
Place to override default theme colors.")
(custom-autoload 'kanagawa-themes-custom-colors "kanagawa-themes" t)
(when (and (boundp 'custom-theme-load-path) load-file-name) (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "kanagawa-themes" '("kanagawa-themes-"))

;;; End of scraped data

(provide 'kanagawa-themes-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; kanagawa-themes-autoloads.el ends here
